// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvNASwEmE8Ggpj2kf4UpghUhhV_WWY56k',
    appId: '1:1069833160424:web:8f004b9fdd813ff6b4eb5d',
    messagingSenderId: '1069833160424',
    projectId: 'yalova-wonder-kids',
    authDomain: 'yalova-wonder-kids.firebaseapp.com',
    storageBucket: 'yalova-wonder-kids.firebasestorage.app',
    measurementId: 'G-TCQDCFZ8DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPNoldMdTjOSC7VhXlP6Pv2Vy9xHLJ6fQ',
    appId: '1:1069833160424:android:16ff51cf1ebda60bb4eb5d',
    messagingSenderId: '1069833160424',
    projectId: 'yalova-wonder-kids',
    storageBucket: 'yalova-wonder-kids.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEkYBDtdN-2nuIb566IcDWTosHUGqX2Yw',
    appId: '1:1069833160424:ios:936c120528ed0fd3b4eb5d',
    messagingSenderId: '1069833160424',
    projectId: 'yalova-wonder-kids',
    storageBucket: 'yalova-wonder-kids.firebasestorage.app',
    iosBundleId: 'com.yalovawonderkids.ywk',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEkYBDtdN-2nuIb566IcDWTosHUGqX2Yw',
    appId: '1:1069833160424:ios:936c120528ed0fd3b4eb5d',
    messagingSenderId: '1069833160424',
    projectId: 'yalova-wonder-kids',
    storageBucket: 'yalova-wonder-kids.firebasestorage.app',
    iosBundleId: 'com.yalovawonderkids.ywk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvNASwEmE8Ggpj2kf4UpghUhhV_WWY56k',
    appId: '1:1069833160424:web:38aaf48675040b6cb4eb5d',
    messagingSenderId: '1069833160424',
    projectId: 'yalova-wonder-kids',
    authDomain: 'yalova-wonder-kids.firebaseapp.com',
    storageBucket: 'yalova-wonder-kids.firebasestorage.app',
    measurementId: 'G-X0C741EN0W',
  );
}
